/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import koneksiDB.koneksi;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class absenuser extends javax.swing.JFrame {

    private DefaultTableModel model;

    /**
     * Creates new form absenuser
     */
    public absenuser() {
        initComponents();
        setLocationRelativeTo(null);
        model = new DefaultTableModel();
        tbl_absen.setModel(model);
        model.addColumn("ID Karyawan");
        model.addColumn("Nama Karyawan");
        model.addColumn("Jabatan");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Jenis Absen");
        model.addColumn("Waktu Absen");
        getData();
//        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//        Dimension frameSize = getSize();
//        setLocation((screenSize.width - frameSize.width)/2,(screenSize.height-frameSize.height)/2);
    }
    
    
    public String idKry;
    public String getID() {
        return idKry.toString();
    }
    
    public void itemTerpilih(){                              
        Data_Search6 DS = new Data_Search6();
        DS.au = this;
        tid.setText(idKry);
    }

    public void getData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            st = (Statement) koneksi.getKoneksi().createStatement();
            String sql =  "select distinct "
                        + "  p.`karyawanID`, k.nama, k.jabatan, k.jk, jenis_absen, waktu_absen "
                        + "from presensi p, karyawan k "
                        + "where p.`karyawanID` = k.`karyawanID` order by waktu_absen desc;";
            ResultSet res = st.executeQuery(sql);
            while (res.next()) {
                Object[] obj = new Object[7];
                obj[0] = res.getString("karyawanID");
                obj[1] = res.getString("nama");
                obj[2] = res.getString("jabatan");
                obj[3] = res.getString("jk");
                obj[4] = res.getString("jenis_absen");
                obj[5] = res.getString("waktu_absen");
                model.addRow(obj);
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        absenOption = new javax.swing.JComboBox();
        bsubmit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bcari = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tnama = new javax.swing.JLabel();
        tjbt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_absen = new javax.swing.JTable();
        searchKaryawanButton = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("MASUKAN ID KARYAWAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 120, 214, 22);

        tid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tidKeyPressed(evt);
            }
        });
        getContentPane().add(tid);
        tid.setBounds(260, 160, 120, 27);

        absenOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masuk", "Keluar" }));
        getContentPane().add(absenOption);
        absenOption.setBounds(270, 210, 90, 22);

        bsubmit.setText("SUBMIT");
        bsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(bsubmit);
        bsubmit.setBounds(270, 250, 89, 40);

        jButton2.setText("HOME");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 280, 67, 25);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("PRESENSI PEGAWAI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel2)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 830, 80);

        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        getContentPane().add(bcari);
        bcari.setBounds(390, 160, 66, 25);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        tnama.setText("Nama ");

        tjbt.setText("Jabatan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tjbt)
                    .addComponent(tnama))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(tnama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(tjbt)
                .addGap(63, 63, 63))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 170, 193, 232);

        tbl_absen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_absen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_absenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl_absenMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_absen);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 430, 540, 130);

        searchKaryawanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/gif/16x16/Text preview.gif"))); // NOI18N
        searchKaryawanButton.setText("Search Karyawan");
        searchKaryawanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKaryawanButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchKaryawanButton);
        searchKaryawanButton.setBounds(470, 160, 153, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void selectData() {
        int i = tbl_absen.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "Tidak ada data terpilih!");
            return;
        }
        tid.setText("" + model.getValueAt(i, 0));
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Tampilan_awal().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        //new absenuser().setVisible(false);
        absenuser au = new absenuser();
        au.setVisible(false);
        Tampilan_awal awal = new Tampilan_awal();
        awal.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    protected void datatable(String karyawanId) {
        Object[] Baris = {"Waktu Absen", "Jenis Absen", "Nama Karyawan", "Karyawan ID"
        };
        model = new DefaultTableModel(null, Baris);
        tbl_absen.setModel(model);
        String sql = "select p.waktu_absen, p.jenis_absen, k.nama, k.jabatan, k.karyawanID from karyawan k, presensi p"
                + "where k.karyawanID = p.karyawanID and k.karyawanID = " + karyawanId;
        try {
            st = (Statement) koneksi.getKoneksi().createStatement();
            ResultSet hasil = st.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("waktu_absen");
                String b = hasil.getString("jenis_absen");
                String c = hasil.getString("nama_karyawan");
                String d = hasil.getString("jabatan");
                String e = hasil.getString("karyawanID");

                String[] data = {a, b, c, d, e};
                model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        // TODO add your handling code here:
        getKaryawan(tid.getText());
        
    }//GEN-LAST:event_bcariActionPerformed

    private void tidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tidKeyPressed
        // TODO add your handling code here:
        loadData();
        int kode = evt.getKeyCode();
        if (kode == KeyEvent.VK_ENTER) {
            getKaryawan(nip);
        }
    }//GEN-LAST:event_tidKeyPressed

    private void bsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubmitActionPerformed
        // TODO add your handling code here:
        absenNow();
        getData();
    }//GEN-LAST:event_bsubmitActionPerformed

    private void tbl_absenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_absenMouseClicked
        // TODO add your handling code here:
//        selectData();

        int rows = tbl_absen.getSelectedRow();
        String a = model.getValueAt(rows, 0).toString();
    }//GEN-LAST:event_tbl_absenMouseClicked

    private void tbl_absenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_absenMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_absenMouseEntered

    private void searchKaryawanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKaryawanButtonActionPerformed
        Data_Search6 DS = new Data_Search6();
        DS.au = this;
        DS.setVisible(true);
        DS.setResizable(false);
        tid.requestFocus();
    }//GEN-LAST:event_searchKaryawanButtonActionPerformed

    private String nip, absenOpt;

    public void loadData() {
        nip = tid.getText();
        absenOpt = (String) absenOption.getSelectedItem();
    }
    private static Statement st;

    private void getKaryawan(String id) {
        try {
            st = (Statement) koneksi.getKoneksi().createStatement();
            String sql = "SELECT nama, jabatan FROM karyawan WHERE karyawanID = '" + id + "'";
            ResultSet res = st.executeQuery(sql);
            res.next();

            String name = res.getString("nama");
            tnama.setText(name);

            String jabatan = res.getString("jabatan");
            tjbt.setText(jabatan);

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }

    private void absenNow() {
        loadData();
        try {
            st = (Statement) koneksi.getKoneksi().createStatement();
//        String sql = "Insert into karyawan(nama,tgl_lahir,jk,alamat,noHP,jabatan,golongan)"
//                +"values('"+vNm+"','"+vTgl+"','"+vJk+"','"+vAl+"','"+vHp+"','"+vJbt+"','"+vGol+"')";
            System.out.println(absenOpt);
            String sql = "Insert into presensi(waktu_absen, jenis_absen, karyawanID) values (now(), '" + absenOpt + "', '" + nip + "')";
            PreparedStatement p = (PreparedStatement) koneksi.getKoneksi().prepareStatement(sql);
            p.executeUpdate(sql);
            tid.requestFocus();
            JOptionPane.showMessageDialog(null, "Absensi Berhasil!");
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Absensi Gagal! : " + err);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(absenuser.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(absenuser.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(absenuser.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(absenuser.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new absenuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox absenOption;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bsubmit;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchKaryawanButton;
    private javax.swing.JTable tbl_absen;
    private javax.swing.JTextField tid;
    private javax.swing.JLabel tjbt;
    private javax.swing.JLabel tnama;
    // End of variables declaration//GEN-END:variables
}
