/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author syahrul
 */
public class Form_Utama extends javax.swing.JFrame {

    /**
     * Creates new form Form_Utama
     */
    public Form_Utama() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mUtama = new javax.swing.JMenuBar();
        mData = new javax.swing.JMenu();
        dKaryawan = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        dLembur = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        dPenggajian = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mLaporan = new javax.swing.JMenu();
        lKaryawan = new javax.swing.JMenuItem();
        lPenggajian = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mKeluar = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(160, 30));
        setSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Welcome Pt Putra Tunggal Jakarta");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 190, 632, 52);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Sistem Aplikasi Penggajian Karyawan ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 250, 454, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ICONPT (2).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 70, 118, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BackUtama.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -60, 890, 540);

        mData.setText("DATA MASTER");
        mData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mDataMouseClicked(evt);
            }
        });

        dKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_employee_24px_2.png"))); // NOI18N
        dKaryawan.setText("Form Karyawah");
        dKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dKaryawanMouseClicked(evt);
            }
        });
        dKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dKaryawanActionPerformed(evt);
            }
        });
        mData.add(dKaryawan);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Form Absensi");
        jCheckBoxMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_attendance_24px_1.png"))); // NOI18N
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        mData.add(jCheckBoxMenuItem1);

        dLembur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_test_results_24px_1.png"))); // NOI18N
        dLembur.setText("Form Penilaian");
        dLembur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dLemburMouseClicked(evt);
            }
        });
        dLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dLemburActionPerformed(evt);
            }
        });
        mData.add(dLembur);

        mUtama.add(mData);

        jMenu1.setText("TRANSAKSI");

        dPenggajian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_money_transfer_24px_1.png"))); // NOI18N
        dPenggajian.setText("DATA Penggajian");
        dPenggajian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dPenggajianMouseClicked(evt);
            }
        });
        dPenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dPenggajianActionPerformed(evt);
            }
        });
        jMenu1.add(dPenggajian);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/give-money.png"))); // NOI18N
        jMenuItem1.setText("DATA Tunjangan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("DATA Kesejahteraan");
        jMenu1.add(jMenuItem2);

        mUtama.add(jMenu1);

        mLaporan.setText("LAPORAN");

        lKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_test_results_24px_1.png"))); // NOI18N
        lKaryawan.setText("Laporan Karyawan");
        lKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lKaryawanActionPerformed(evt);
            }
        });
        mLaporan.add(lKaryawan);

        lPenggajian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_test_results_24px_1.png"))); // NOI18N
        lPenggajian.setText("Laporan Penggajian");
        lPenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lPenggajianActionPerformed(evt);
            }
        });
        mLaporan.add(lPenggajian);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_test_results_24px_1.png"))); // NOI18N
        jMenuItem3.setText("Laporan Absensi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mLaporan.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_test_results_24px_1.png"))); // NOI18N
        jMenuItem4.setText("Laporan Penilaian");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mLaporan.add(jMenuItem4);

        mUtama.add(mLaporan);

        mKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Logout_24px.png"))); // NOI18N
        mKeluar.setText("LOGOUT");
        mKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mKeluarMouseClicked(evt);
            }
        });
        mKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKeluarActionPerformed(evt);
            }
        });
        mUtama.add(mKeluar);

        setJMenuBar(mUtama);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dKaryawanActionPerformed
        new Form_Karyawan().setVisible(true);
    }//GEN-LAST:event_dKaryawanActionPerformed

    private void dLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dLemburActionPerformed
        new Form_PenilaianKaryawan().setVisible(true);
    }//GEN-LAST:event_dLemburActionPerformed

    private void dPenggajianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dPenggajianActionPerformed
        new Form_Penggajian().setVisible(true);
    }//GEN-LAST:event_dPenggajianActionPerformed

    private void mKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKeluarActionPerformed

    }//GEN-LAST:event_mKeluarActionPerformed

    private void mKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mKeluarMouseClicked
        int i = JOptionPane.showConfirmDialog(null, "Apakah anda yakin Keluar?","Konfrmasi",JOptionPane.YES_NO_OPTION);
        if(i==JOptionPane.YES_OPTION){
            this.dispose();
            new Form_Login().setVisible(true); 
        }
    }//GEN-LAST:event_mKeluarMouseClicked

    private void mDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mDataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mDataMouseClicked

    private void dKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dKaryawanMouseClicked

    }//GEN-LAST:event_dKaryawanMouseClicked

    private void dLemburMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dLemburMouseClicked

    }//GEN-LAST:event_dLemburMouseClicked

    private void dPenggajianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dPenggajianMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dPenggajianMouseClicked

    private void lKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lKaryawanActionPerformed
        new Lap_Karyawan().setVisible(true);
    }//GEN-LAST:event_lKaryawanActionPerformed

    private void lPenggajianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lPenggajianActionPerformed
        new Lap_Penggajian().setVisible(true);
    }//GEN-LAST:event_lPenggajianActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
     new absenuser().setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         new Lap_Absensi().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       new Form_Tunjangan().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new Lap_Penilaian().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dKaryawan;
    private javax.swing.JMenuItem dLembur;
    private javax.swing.JMenuItem dPenggajian;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem lKaryawan;
    private javax.swing.JMenuItem lPenggajian;
    private javax.swing.JMenu mData;
    private javax.swing.JMenu mKeluar;
    private javax.swing.JMenu mLaporan;
    private javax.swing.JMenuBar mUtama;
    // End of variables declaration//GEN-END:variables
}
