/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksiDB.inikoneksi;

/**
 *
 * @author ASUS
 */
public class Form_Penilaian extends javax.swing.JFrame {
 private Connection conn = new inikoneksi().connect();
 private DefaultTableModel tabmode;
    /**
     * Creates new form Form_PenilaianKaryawan
     */
    public Form_Penilaian() {
        initComponents();
    }
    protected void aktif(){
        tid.setEnabled(true);
        tnama.setEnabled(true);
        tjabatan.setEnabled(true);
        tabsen.setEnabled(true);
        tid.requestFocus();
     } 
       protected void kosong(){
        tid.setText("");
        tnama.setText("");
        tjabatan.setText("");
        tabsen.setText("");
        tpk.setSelectedIndex(0);
       }
       protected void datatable(){
        Object[] Baris ={"id karyawan","Nama Karyawan","Jabatan","tunjangan"  
        };
        tabmode = new DefaultTableModel(null, Baris);
        tabeltunjangan.setModel(tabmode);
        String sql= "select * from tunjangan";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_karyawan");
                String b = hasil.getString("nama");
                String c = hasil.getString("jabatan");
                String d = hasil.getString("tunjangan");
           
                
                String[] data ={a,b,c,d};
                tabmode.addRow(data);
            }
        } catch(Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        tjabatan = new javax.swing.JTextField();
        tabsen = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tpk = new javax.swing.JComboBox();
        bsave = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 220, 33, 16);

        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 180, 12, 16);

        jLabel3.setText("Jabatan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 260, 44, 16);

        jLabel4.setText("Jumlah Masuk Dalam 1 bulan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 300, 180, 16);
        getContentPane().add(tid);
        tid.setBounds(440, 180, 90, 22);
        getContentPane().add(tnama);
        tnama.setBounds(440, 220, 90, 22);
        getContentPane().add(tjabatan);
        tjabatan.setBounds(440, 260, 90, 22);

        tabsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabsenActionPerformed(evt);
            }
        });
        getContentPane().add(tabsen);
        tabsen.setBounds(440, 300, 90, 22);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel5.setText("FORM PENILAIAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(jLabel5)
                .addContainerGap(425, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 990, 100);

        jLabel6.setText("Penilaian Karyawan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 340, 130, 16);

        tpk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sangat Baik", " Baik", "Kurang Baik", "Sangat Tidak Baik" }));
        getContentPane().add(tpk);
        tpk.setBounds(440, 340, 100, 22);

        bsave.setText("SAVE");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        getContentPane().add(bsave);
        bsave.setBounds(570, 240, 63, 25);

        bedit.setText("EDIT");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        getContentPane().add(bedit);
        bedit.setBounds(650, 240, 59, 25);

        bdelete.setText("DELETE");
        getContentPane().add(bdelete);
        bdelete.setBounds(720, 240, 75, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 390, 850, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabsenActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        // TODO add your handling code here:
        String sql ="insert into penilaian_karyawan value (?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tid.getText());
            stat.setString(2, tnama.getText());
            stat.setString(3, tjabatan.getText());
            stat.setString(4, tabsen.getText());
            stat.setString(5, tpk.getSelectedItem().toString());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            tid.requestFocus();
            datatable();
          
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal disimpan "+e);
        }         
    }//GEN-LAST:event_bsaveActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "update penilaian_karyawan set nama=?,jabatan=?,jumlah_masuk=?,penilaian_karyawan=? where id_karyawan=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tnama.getText());
            stat.setString(2, tjabatan.getText());
            stat.setString(3, tabsen.getText());
            stat.setString(4, tpk.getSelectedItem().toString());            
            stat.setString(5, tid.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil diubah");
            kosong();
            tid.requestFocus();
            datatable(); 
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal diubah"+e);
        }
    }//GEN-LAST:event_beditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Penilaian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tabsen;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tjabatan;
    private javax.swing.JTextField tnama;
    private javax.swing.JComboBox tpk;
    // End of variables declaration//GEN-END:variables
}
